### ISSUE TITLE
Unable to retrieve some URLS

### ISSUE THREAD

**Issue by kelson42** [geoffreak/request-enhanced#1]
Using the following code:
    #!/usr/bin/env node
    "use strict";

```
var request = require( 'request-enhanced' );

var url = 'http://parsoid.wmflabs.org/fa/%D8%A2%D8%B0%D8%B1_%D8%A8%DB%8C%DA%AF%D8%AF%D9%84%DB%8C?oldid=9585495';
request.get( url , function( error, body ) {
    if ( error ) {
        console.log( error );
    } else {
        console.log( "OK" );
    }
});
```

I get:
    $ ./test.js 
    { [Error: ETIMEDOUT error on http://parsoid.wmflabs.org/fa/%D8%A2%D8%B0%D8%B1_%D8%A8%DB%8C%DA%AF%D8%AF%D9%84%DB%8C?oldid=9585495] code: 'ETIMEDOUT' }

This is strange, this should work because:
    $ curl -I http://parsoid.wmflabs.org/fa/%D8%A2%D8%B0%D8%B1_%D8%A8%DB%8C%DA%AF%D8%AF%D9%84%DB%8C?oldid=9585495
    HTTP/1.1 200 OK
    X-Powered-By: Express
    Access-Control-Allow-Origin: *
    Cache-Control: s-maxage=2592000
    Content-Type: text/html; charset=UTF-8
    X-Parsoid-Performance: duration=15436; start=1383919023036
    Date: Fri, 08 Nov 2013 13:57:18 GMT
    Connection: keep-alive

page is available....

**Comment by geoffreak** [comment]
This appears to be an issue of the timeout not being long enough. When I used Postman and cURL, this server was taking upwards of 15 seconds to respond. request-enhanced has a default timeout of only 10 seconds, so it will need to be lengthened for this request. This code worked for me (using a 20 second timeout instead of 10):

``` javascript
var request = require( 'request-enhanced' );

var url = 'http://parsoid.wmflabs.org/fa/%D8%A2%D8%B0%D8%B1_%D8%A8%DB%8C%DA%AF%D8%AF%D9%84%DB%8C?oldid=9585495';
request.get( {url: url , timeout: 20000}, function( error, body ) {
    if ( error ) {
        console.log( error );
    } else {
        console.log( "OK" );
    }
});
```

**Comment by kelson42** [comment]
Thank you for your answer. This works for me too. Seeing the scrip "dying" after ~3 minutes puzzled me. I thought this was more or less the value of the timeout itself...
